#!/bin/bash

# Collecting necessary information
userName=$(whoami)
currentDate=$(date "+%F %T")
hostName=$(hostname)
#Here the command hostnamectl extracts important information of system and grep filters the output to select operating system while sed further filters
# the output to remove the label operating system
OS=$(hostnamectl | grep "Operating System" | sed 's/Operating System: //')
#Here the uptime -p extracts the system uptime while sed deleted the up word from the line
upTime=$(uptime -p | sed 's/^up //')
 
#Here the lscpu extrects the information of cpu while grep filters the output to model name label and sed removes the label model name and any leading
#spaces
informationAboutCpu=$(lscpu | grep 'Model name' | sed 's/Model name:\s*//')
#Here the  speed of cpu is extracted by cat /proc/cpuinfo which is further given to grep for filtering only the speed of cpu which is passed to head
#for extracting the first line which is further passed to cut for formatting and sed further formats the output
speedOfCpu=$(cat /proc/cpuinfo | grep "cpu MHz" | head -1 |cut -d':' -f2 | sed 's/^ *//')
maxSpeedOfCpu=$(cat /proc/cpuinfo | grep "cpu MHz" | head -1 | cut -d':' -f2 | sed 's/^ *//' )
#Here the information of ram is given by free -h which is further given to grep for selecting the MEm: option and which is further given to awk for 
#formatting
informationOfRam=$(free -h | grep "Mem:" | awk '{print $2}')
#Here the command extracts the information about disk name, size and model which is further processed to grep for filtering in which it will filter 
#names other than loop 
diskInformation=$(lsblk -o NAME,SIZE,MODEL | grep -vE "NAME|loop")
#Used to extract the information of vido card which is further processed to grep for filtering and which is further processed to sed for formatting
videoInformation=$(sudo lshw -C display | grep "product:" | sed 's/product:\s*//')
# Displays the name of fully qualified domain
fqdn=$(hostname -f)
# Displays the hostname and only prints the first field of line
hostAddress=$(hostname -I | awk '{print $1}')
#Extracts the gateway adress by looking at the routing table and formatting the necessary information 
gatewayAdress=$(ip r s default | cut -d' ' -f3)
#Run as super-user it extracts the information about nameserver from /etc/resolv.conf file and the head command formats the output by extracting
#First ten or first line and then passing to awk for further processing and extracting the field of column 2
dnsServer=$(sudo grep nameserver /etc/resolv.conf | head -1 | awk '{print $2}')
#It extracts the interface name 
interfaceName=$(ip r | grep default | awk '{print $5}')
#It gives us the ip address in cidr format of the interfaces selected above. It gives the ip address of any  interfaces dynamically
interfaceIP=$(ip a s | awk '/inet .* global/ {print $2}')
#Used to get users logged into the system 
currentlyLogedInUsers=$(who | awk '{print $1}' )
#ps command counts the process count and passes it to wc -l to count the total number of process running
processCount=$(ps | wc -l)
#Calculates the load averages by extracting the information from uptime and passing it to awk for being formatted
loadAverages=$(uptime | awk '{print $10, $11, $12}')
#The free memory is searched by using free -h command and they grep filters it to necessary requirements which is further passed to awk for formatting
allocationOfMemory=$(free -h | grep "Mem:" | awk '{print $4}')
#Gives us the total number of listening ports 
listeningNetworkPorts=$(ss -l | wc -l)
#Generates the rules of ufw in number form
ufwRules=$(sudo ufw status numbered)
# Generate the report
cat <<EOF

System Report generated by $userName, $currentDate

System Information
------------------
Hostname: $hostName
OS: $OS
Uptime: $upTime

Hardware Information
--------------------
CPU: $informationAboutCpu
Speed: Current Speed $speedOfCpu MHz, Maximum Speed $maxSpeedOfCpu MHz
RAM: $informationOfRam
$diskInformation
Video: $videoInformation

Network Information
-------------------
FQDN: $fqdn
Host Address: $hostAddress
Gateway IP: $gatewayIp
DNS Server: $dnsServer
Interface Name: $interfaceName
Interface IP: $interfaceIP 

System Status
-------------
Users Logged In: $currentlyLogedInUsers
Disk Space: FREE SPACE FOR LOCAL FILESYSTEMS IN FORMAT: 
Process Count: $processCount 
Load Averages: $loadAverages
Memory Allocation: $allocationOfMemory
Listening Network Ports: $listeningNetworkPorts
UFW Rules: $ufwRules
EOF



